"""empty message

Revision ID: 3cfcb41e91e6
Revises: 52d907e2de6f
Create Date: 2019-03-10 11:31:29.948750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cfcb41e91e6'
down_revision = '52d907e2de6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('client_adr', sa.String(length=64), nullable=False),
    sa.Column('request', sa.String(length=30), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    # ### end Alembic commands ###
